[features]
seeds = false
[programs.localnet]
sol_tic_tac_toe = "EPrJwhiyKRits37fRmPhnpCSduZ4XKJDZXnBQs87J5Fu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ksh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
